# http://blog.stablekernel.com/continuous-integration-for-unity-5-using-travisci
# https://docs.travis-ci.com/user/osx-ci-environment/

sudo: required

os: osx
osx_image: xcode8.3

before_install:
  - go version
  - chmod a+x ./scripts/*.sh
  - chmod a+x ./setup_proj.sh

install:
  - go get -u github.com/davecgh/go-spew/spew
  - cd scripts; ./install_unity.sh; cd -

script:
  - go build
  - ./setup_proj.sh

  # standalone windows
  - cd scripts; ./install_standalone_win.sh; cd -
  - ./scripts/build_standalone_win_dev.sh
  - ./scripts/build_vr_win32_steamvr_dev.sh
  - ./scripts/build_vr_win32_oculus_dev.sh

  # ios
  - cd scripts; ./install_ios.sh; cd -
  - ./scripts/build_ios.sh

  # show build output
  - ls -al ./output


notifications:
  email: false
