# http://blog.stablekernel.com/continuous-integration-for-unity-5-using-travisci
# https://docs.travis-ci.com/user/osx-ci-environment/

sudo: required

os: osx
osx_image: xcode8.3

cache:
  directories:
  - scripts/unity-installers/

before_install:
  - go version
  - chmod a+x ./*.sh
  - chmod a+x ./scripts/*.sh
  - mkdir -p scripts/unity-installers/

install:
  - go get -u github.com/davecgh/go-spew/spew
  # unity editor
  - cd scripts; ./install.sh editor; cd -
  # standalone windows
  - cd scripts; ./install.sh windows; cd -

script:
  - go test -v ./...
  - go build

  - ./minamo -cmd=show -config=./configs/standalone_win_dev.json -field=minamo_version

  - ./run_test.sh
  - cat ./results.xml

  - ./export_package.sh
  - ls -al ./dist

  # standalne win dev
  - CONFIG=./configs/standalone_win_dev.json
  - ./minamo -cmd=dump -config=$CONFIG
  - ./minamo -cmd=build -config=$CONFIG -log=unity_standalone_win_dev.log
  - cat unity_standalone_win_dev.log | grep "MinamoLog"
  - ls -al ./output/ | grep standalone_win_dev

  # vr win32 steam dev
  - CONFIG=./configs/vr_win32_steamvr_dev.json
  - ./minamo -cmd=dump -config=$CONFIG
  - ./minamo -cmd=build -config=$CONFIG -log=unity_vr_win32_steamvr_dev.log
  - cat unity_vr_win32_steamvr_dev.log | grep "MinamoLog"
  - ls -al ./output/ | grep vr_win32_steamvr_dev

  # vr win32 oculus dev
  - CONFIG=./configs/vr_win32_oculus_dev.json
  - ./minamo -cmd=dump -config=$CONFIG
  - ./minamo -cmd=build -config=$CONFIG -log=unity_vr_win32_oculus_dev.log
  - cat unity_vr_win32_oculus_dev.log | grep "MinamoLog"
  - ls -al ./output/ | grep vr_win32_oculus_dev

after_script:
  # unity log
  - cat test.log
  - cat export.log
  - cat unity_standalone_win_dev.log
  - cat unity_vr_win32_steamvr_dev.log
  - cat unity_vr_win32_oculus_dev.log

deploy:
  provider: releases
  api_key:
    secure: gutLcLAJmDlsDhsrNebGh4EUHLC8uaOaDtG+Bsk/1TFqV1U9DcTfEzb6r1ajZVb1Wm2MZe0tyjTGVOQbLblsHqrDt+FkJIYCeCeA/sBpQZ4gSjVUtAaG3dA8amoYhqH4oBHKe/EjOKled5VUXQhniSfhDKjVgKgl3+IQ4htBYtggKG+gCfSqZA7XNscUYkL9DmkAc0lhKTJsmZ6uTxNa7mhAzmY2fW/vRmGIUhCAJFfBM5iD4I53ekgOmLsOtqoy+EnFQ+e2qsKNdTOGJLCwmJlE+6tw1zlu2tTYZtX1fUJICBySS0j/hahSK982kNzUEtd0PxCpIAIJsJEcVU0nkvZtr+fvXbh92foxKSPmmNWfAzEyFPzXiX78zuJ+dg7NwAP27PLSg/VkFQQSgIByoy66W73DIX9fLBuxxsm+EzHfE88g5u9LihqDAN2xNW5ym8AnxdCQJGUKjk22Rn8oQxCiPDURf779r9lls1KbNIh9mPqx3ngNQDjuKUbZizNpn2Yw8baiMeJi+IVNQWcVhguAsfBxNxyNvtZXv8G7h8jxJO2d1TTM6Z/ihytc/vXb1fDOlAGe6+Hv0T4F9W9r1JnLJq9V1QFB1rHcfRnTDY9s4QVA8wFCrrp78WSVCsoXCOASioVyMAoqMV5LqRMOoKUGmfgmR3B30BKAY4PNtXk=
  file: dist/minamo.unitypackage
  skip_cleanup: true
  on:
    tags: true

# jobs:
#   include:
#     - stage: Golang unit test
#       script: go test -v ./...

#     - stage: Unity3D unit test
#       script: ./run_test.sh

#     - stage: Export package
#       script: ./export_package.sh

#     - stage: Build standalone_win_dev.json
#       before_script: go build
#       script: ./scripts/build_standalone_win_dev.sh
#       after_script: ls -al ./output

#     - stage: Build vr_win32_steamvr_dev.json
#       before_script: go build
#       script: ./scripts/build_vr_win32_steamvr_dev.sh
#       after_script: ls -al ./output

#     - stage: Build vr_win32_oculus_dev.json
#       before_script: go build
#       script: ./scripts/build_vr_win32_oculus_dev.sh
#       after_script: ls -al ./output

notifications:
  email: false

# https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches
branches:
  only:
  - master
