# http://blog.stablekernel.com/continuous-integration-for-unity-5-using-travisci
# https://docs.travis-ci.com/user/osx-ci-environment/

sudo: required

os: osx
osx_image: xcode8.3

before_install:
  - go version
  - chmod a+x ./scripts/*.sh
  - chmod a+x ./setup_proj.sh

install:
  - go get -u ./...
  - cd scripts; ./install.sh editor; cd -

script:
  - go test -v ./...
  - go build

  - ./setup_proj.sh

  # standalone windows
  - cd scripts; ./install.sh windows; cd -
  - ./scripts/build_standalone_win_dev.sh
  - ./scripts/build_vr_win32_steamvr_dev.sh
  - ./scripts/build_vr_win32_oculus_dev.sh

  # show build output
  - ls -al ./output


notifications:
  email: false

# https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches
branches:
  only:
  - master
