# http://blog.stablekernel.com/continuous-integration-for-unity-5-using-travisci

language: objective-c
osx_image: xcode8.1

before_install:
  - chmod a+x ./scripts/install.sh
  - chmod a+x ./scripts/build.sh
  - chmod a+x ./setup_proj.sh

install:
  - go get -u -v
  - ./scripts/install.sh

script:
  - go build
  - ./setup_proj.sh
  - ./scripts/build.sh

notifications:
  email: false
