# http://blog.stablekernel.com/continuous-integration-for-unity-5-using-travisci
# https://docs.travis-ci.com/user/osx-ci-environment/

sudo: required

os: osx
osx_image: xcode8.3

cache:
  directories:
  - scripts/unity-installers/

before_install:
  - go version
  - chmod a+x ./*.sh
  - chmod a+x ./scripts/*.sh
  - mkdir -p scripts/unity-installers/

install:
  - go get -u github.com/davecgh/go-spew/spew
  # unity editor
  - cd scripts; ./install.sh editor; cd -
  # standalone windows
  - cd scripts; ./install.sh windows; cd -

script:
  - go test -v ./...
  - go build

  - ./run_test.sh
  - ./export_package.sh
  - ./scripts/build_standalone_win_dev.sh
  - ./scripts/build_vr_win32_steamvr_dev.sh
  - ./scripts/build_vr_win32_oculus_dev.sh

after_script:
  - ls -al ./output

# jobs:
#   include:
#     - stage: Golang unit test
#       script: go test -v ./...

#     - stage: Unity3D unit test
#       script: ./run_test.sh

#     - stage: Export package
#       script: ./export_package.sh

#     - stage: Build standalone_win_dev.json
#       before_script: go build
#       script: ./scripts/build_standalone_win_dev.sh
#       after_script: ls -al ./output

#     - stage: Build vr_win32_steamvr_dev.json
#       before_script: go build
#       script: ./scripts/build_vr_win32_steamvr_dev.sh
#       after_script: ls -al ./output

#     - stage: Build vr_win32_oculus_dev.json
#       before_script: go build
#       script: ./scripts/build_vr_win32_oculus_dev.sh
#       after_script: ls -al ./output

notifications:
  email: false

# https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches
branches:
  only:
  - master
