# http://blog.stablekernel.com/continuous-integration-for-unity-5-using-travisci
# https://docs.travis-ci.com/user/osx-ci-environment/

sudo: required

os: osx
osx_image: xcode8.3

before_install:
  - go version
  - chmod a+x ./scripts/install.sh
  - chmod a+x ./scripts/build.sh
  - chmod a+x ./setup_proj.sh

install:
  - go get -u github.com/davecgh/go-spew/spew
  - ./scripts/install.sh

script:
  - go build
  - ./setup_proj.sh
  - ./scripts/build.sh

notifications:
  email: false
